name: umbrella
version: 0.1.0.0
github: "xzhavilla/umbrella"
license: BSD3
author: "Alberto Villa"
maintainer: "villa.alberto@gmail.com"
copyright: "2021 Alberto Villa"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/xzhavilla/umbrella#readme>

dependencies:
  - base >= 4.7 && < 5
  - ilist
  - mtl
  - random
  - split

library:
  source-dirs: src

executables:
  umbrella-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - umbrella
    when:
      - condition: false
        other-modules: Paths_umbrella

tests:
  umbrella-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - umbrella
    when:
      - condition: false
        other-modules: Paths_umbrella
